apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echoserver-v2-secure
  namespace: default
spec:
  ingressClassName: external-nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Exact
            backend:
              service:
                name: aks-helloworld
                port:
                  number: 80
