apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echoserver-v2-secure
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-targer: /
spec:
  ingressClassName: external-nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: aks-helloworld
            port:
              number: 80
