apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: sas-test-app
  namespace: flux-system
spec:
  secretRef:
    name: regcred
  image: sasaksacrtest.azurecr.io/sas-test-app
  interval: 1m
