apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: sas-test-app
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: sas-test-app
  policy:
    semver:
      range: '>= 1.0.0 <2.0.0'
