apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-helloworld
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aks-helloworld
  template:
    metadata:
      labels:
        app: aks-helloworld
    spec:
      containers:
      - name: aks-helloworld
        image: sasaksacrtest.azurecr.io/sas-test-app:1.1.0 # {"$imagepolicy": "flux-system:sas-test-app"}
        ports:
        - name: http
          containerPort: 3000
